// data copied from ftp02.portlandoregon.gov/civicApps

config.layers.push(
   { 'name': "Benchmark pdx", 'url':
 "ftp://ftp02.portlandoregon.gov/CivicApps/Benchmark_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Bicycle Network pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Bicycle_Network_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Bicycle Parking pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Bicycle_Parking_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Bridges pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Bridge_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Business Associations pdx", 'symbolField': 'NAME', 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Business_Associations_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "business licenses", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/business_licenses.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "CIP Data", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/CIP_Data.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "CIP Data pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/CIP_Data_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Cities pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Cities_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "City metro", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/City_metro.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Contract Jobs Line pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Contract_Jobs_Line_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Contract Jobs MultiPoint pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Contract_Jobs_MultiPoint_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "cop fiber hut cand sts", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/cop_fiber_hut_cand_sts.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Counties pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Counties_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "County metro", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/County_metro.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2004", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2004.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2005", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2005.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2006", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2006.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2007", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2007.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2008", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2008.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2009", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2009.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2010", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2010.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2011", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2011.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2012", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2012.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "crime incident data 2013", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/crime_incident_data_2013.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Curb Ramp pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Curb_Ramp_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Curb Ramps pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Curb_Ramps_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Development Opp Areas pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Development_Opp_Areas_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Development Opportunity Areas pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Development_Opportunity_Areas_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Enterprise ECommerce Zone pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Enterprise_ECommerce_Zone_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Freight Districts pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Freight_Districts_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Freight Facilities pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Freight_Facilities_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Guardrail pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Guardrail_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Heritage Trees pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Heritage_Trees_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "HomeBuyer Opportunity Areas pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/HomeBuyer_Opportunity_Areas_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Intermodal Facilities pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Intermodal_Facilities_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "ITS Camera pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/ITS_Camera_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "ITS Sign pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/ITS_Sign_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Leaf Pickup pdx", 'symbolField': 'COMMENTS', 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Leaf_Pickup_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "LID Boundaries pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/LID_Boundaries_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "LID Streets pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/LID_Streets_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "LTA HomeBuyer Opportunity pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/LTA_HomeBuyer_Opportunity_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Neighborhoods pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Neighborhoods_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Parking Meter pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Parking_Meter_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Parking Meters pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Parking_Meters_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Parks Desired Future cond pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Parks_Desired_Future_cond_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Parks Easements pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Parks_Easements_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Parks pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Parks_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Parks Taxlots pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Parks_Taxlots_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Parks Trails pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Parks_Trails_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Parks Vegetation Surveys pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Parks_Vegetation_Surveys_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Pavement Maint pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Pavement_Maint_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Pavemoratorium", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Pavemoratorium.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Pavemoratorium pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Pavemoratorium_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "PDOT Snow Ice Routes pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/PDOT_Snow_Ice_Routes_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Pedestrian Districts pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Pedestrian_Districts_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Permit Jobs Line pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Permit_Jobs_Line_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Permit Jobs Point pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Permit_Jobs_Point_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Permit Jobs Polygon pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Permit_Jobs_Polygon_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Portland Street Sweeping", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Portland_Street_Sweeping.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Portland Streets Permit Jobs Line", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Portland_Streets_Permit_Jobs_Line.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Portland Streets Permit Jobs Point", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Portland_Streets_Permit_Jobs_Point.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Portland Streets Permit Jobs Polygon", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Portland_Streets_Permit_Jobs_Polygon.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Portland Transit Stations", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Portland_Transit_Stations.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Portland TSP Classifications", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Portland_TSP_Classifications.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Portland TSP District Boundaries", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Portland_TSP_District_Boundaries.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "ProtectionZones", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/ProtectionZones.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "public art", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/public_art.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Signage Lighting Imp Prog pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Signage_Lighting_Imp_Prog_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Signage Lighting Improvement Program pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Signage_Lighting_Improvement_Program_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Snow Ice Routes pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Snow_Ice_Routes_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Storefront Imp Areas pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Storefront_Imp_Areas_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Storefront Improvement Areas pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Storefront_Improvement_Areas_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Street Contract Jobs line pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Street_Contract_Jobs_line_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Street Contract Jobs multipoint pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Street_Contract_Jobs_multipoint_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Street Lights pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Street_Lights_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Street Sweeping pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Street_Sweeping_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Street Trees pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Street_Trees_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Traffic Calming pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Traffic_Calming_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Traffic Signal pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Traffic_Signal_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Transit Stations pdx", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Transit_Stations_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Transportation System Plan Classifications", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/TSP_Classifications_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Transportation System Plan District Boundaries", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/TSP_District_Boundaries_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Underground Wiring Districts", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Underground_Wiring_Districts_pdx.zip", 'symbolField': 'District', 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Urban Renewal Areas", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Urban_Renewal_Areas_pdx.zip", 'symbolField': 'URA', 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Watersheds - metro area", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Watersheds_Web_BES_pdx.zip", 'symbolField': 'WATERSHED', 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Wellhead Protection Areas", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/Wellhead_Prot_Areas_pdx.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true },
{ 'name': "Zipcodes - metro district", 'url': "ftp://ftp02.portlandoregon.gov/CivicApps/ZipCode_metro.zip", 'type': 'shapefile', 'source': 'Civic Apps', 'theme': 'General', 'proxy': true }

);